# GLOBAL CONFIGURATION
spring:
    # if you want to set a different profile
    # use environment variable:
    #
    # SPRING_PROFILES_ACTIVE=docker
     # DB: enable web console
    profiles.active: local
    application.name: user-service
        
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    de.muenchen.referenzarchitektur: DEBUG

---
# DOCKER CONFIGURATION
spring:
    profiles: docker

# inside a container, we can always map to 8080. Use your compose
# file to expose a service on a different port.
server.port: 8080


---
# LOCAL CONFIGURATION
spring:
    profiles: local
    
# random server port to avoid port 
# conflicts on localhost
# server.port: 0
# dedicated server port
server.port: 8870
        

security:
  basic:
    enabled: false
  oauth2:
    entitlements:
      entitlementsUri: http://localhost:8080/auth/realms/demo/authz/entitlement/openIdDemo    
    resource:
      filter-order: 3
      jwt:
        key-value: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlsteeVtC+LlM/uhuusceFDvKbeCPolBEpq+rNnRbBvSPDCdKGcIIpjrQswX/58loE/bQ45A5IY1Tlm1MWbGxZ0IZhYaILeTNySTK3aRsV94OpN+ib/PGWkP1aQZ6wdm4//C6whOhCbulbLwSTyjByD72FGdaO/OhrATD9OAEcP0QmrvjLRHQBA80lxB4fRCyIrea9aL/AuvBsAbTz1Ub70rH8ydwaPtev7/L4dY+9NaqoL23pLIYyV7k3cuPeyHU/lt4I68R4rNiFv08zQFWGMr+li13cWNi9KsNfP5h6Ce7h+D2WmOUv7Tm9b8rAJ4jGHuf8ylHWt0SQxBtofuldwIDAQAB
    client:
      client-id: openIdDemo

    #this part not needed when validating the JWT with the public key
#    client:
#    resource:
#      userInfoUri: http://localhost:8080/auth/realms/demo/protocol/openid-connect/userinfo 

---
spring:
    profiles: no-security

server.port: 8080
security.ignored: /**